"""v2.0+ — Studio dashboard: a self-contained static HTML view of a run.

Zero dependencies, inline styles, embedded data — renders in the
workspace preview, opens offline in any browser, prints to PDF.
"""

from __future__ import annotations

import html
import json
from pathlib import Path

TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AEOS Studio — Run</title>
<style>
:root {{ --ink:#161b22; --paper:#0d1117; --card:#161b22; --line:#30363d;
        --good:#3fb950; --bad:#f85149; --warn:#d29922; --accent:#58a6ff; }}
* {{ box-sizing:border-box; }}
body {{ margin:0; background:var(--paper); color:#c9d1d9;
  font:14px/1.5 ui-monospace,"SF Mono",Menlo,Consolas,monospace; }}
.wrap {{ max-width:1000px; margin:0 auto; padding:32px 20px 80px; }}
h1 {{ font-size:20px; color:#fff; }} h1 span {{ color:var(--accent); }}
.grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; margin:20px 0; }}
.stat {{ background:var(--card); border:1px solid var(--line); border-radius:8px; padding:14px; }}
.stat b {{ display:block; font-size:26px; color:#fff; }}
.stat.ok b {{ color:var(--good); }} .stat.bad b {{ color:var(--bad); }}
table {{ width:100%; border-collapse:collapse; margin:16px 0; }}
th,td {{ text-align:left; padding:8px 10px; border-bottom:1px solid var(--line); }}
th {{ color:var(--accent); font-weight:600; }}
.tag {{ padding:2px 8px; border-radius:10px; font-size:11px; }}
.PASS,.SUCCEEDED {{ background:#0f2e17; color:var(--good); }}
.FAIL,.FAILED {{ background:#3d1216; color:var(--bad); }}
.ESCALATED,.SKIPPED {{ background:#3a2c07; color:var(--warn); }}
.timeline {{ background:var(--card); border:1px solid var(--line); border-radius:8px;
  padding:12px 16px; max-height:340px; overflow-y:auto; }}
.ev {{ display:flex; gap:10px; padding:2px 0; }}
.ev .k {{ color:var(--accent); min-width:170px; }}
footer {{ margin-top:40px; color:#8b949e; font-size:12px; }}
</style></head><body><div class="wrap">
<h1>AEOS <span>Studio</span> — run report</h1>
<div class="grid" id="stats"></div>
<h2 style="color:#fff;font-size:15px">Tasks</h2>
<table><thead><tr><th>task</th><th>agent</th><th>state</th><th>attempts</th></tr></thead>
<tbody id="tasks"></tbody></table>
<h2 style="color:#fff;font-size:15px">Event timeline</h2>
<div class="timeline" id="timeline"></div>
<footer>generated by aeos · self-contained · offline</footer>
</div>
<script>
const DATA = {payload};
const stats = document.getElementById("stats");
const kv = [
  ["accepted", DATA.accepted, DATA.accepted ? "ok" : "bad"],
  ["tasks", DATA.summary.tasks ?? "-", ""],
  ["events", DATA.summary.events ?? "-", ""],
  ["success rate", DATA.summary.success_rate ?? "-", ""],
  ["governor", DATA.governor_level ?? "-", ""],
  ["reliability", DATA.governor_reliability ?? "-", ""],
  ["cost $", DATA.economics ? DATA.economics.total_cost : "0", ""],
  ["checkpoints", DATA.checkpoints ?? "-", ""],
];
for (const [label, value, cls] of kv) {{
  const d = document.createElement("div");
  d.className = "stat " + cls;
  d.innerHTML = `<span>${{label}}</span><b>${{value}}</b>`;
  stats.appendChild(d);
}}
const tb = document.getElementById("tasks");
for (const t of DATA.tasks || []) {{
  tb.insertAdjacentHTML("beforeend",
    `<tr><td>${{t.name}}</td><td>${{t.agent}}</td>` +
    `<td><span class="tag ${{t.state}}">${{t.state}}</span></td>` +
    `<td>${{t.attempts}}</td></tr>`);
}}
const tl = document.getElementById("timeline");
for (const e of DATA.events || []) {{
  tl.insertAdjacentHTML("beforeend",
    `<div class="ev"><span class="k">${{e.kind}}</span>` +
    `<span>${{e.detail}}</span></div>`);
}}
</script></body></html>"""


def render_dashboard(bundle: dict, events: list, out: Path) -> Path:
    payload = dict(bundle)
    payload["events"] = [{"kind": e.kind,
                          "detail": html.escape(json.dumps(e.detail,
                                                           default=str))[:160]}
                         for e in events[-120:]]
    payload["tasks"] = [t for t in bundle.get("states_detail", [])] or [
        {"name": k, "agent": "-", "state": v, "attempts": "-"}
        for k, v in bundle.get("states", {}).items()]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(TEMPLATE.format(payload=json.dumps(payload, default=str)),
                   encoding="utf-8")
    return out
